config/routes.rb
Squonk::Application.routes.draw do

 root :to => "home#index"

  resources :quartiers

  resources :villes

  resources :news

  resources :gens

end

app/models/gen.rb
class Gen < ActiveRecord::Base
  attr_accessible :avatar, :dob, :email, :nom, :password, :prenom, :pseudo
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :resource, :texte, :titre
end

app/models/quartier.rb
class Quartier < ActiveRecord::Base
  attr_accessible :coordonnees, :nom
end

app/models/ville.rb
class Ville < ActiveRecord::Base
  attr_accessible :coordonnees, :nom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gens_controller.rb
class GensController < ApplicationController
  # GET /gens
  # GET /gens.json
  def index
    @gens = Gen.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gens }
    end
  end

  # GET /gens/1
  # GET /gens/1.json
  def show
    @gen = Gen.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gen }
    end
  end

  # GET /gens/new
  # GET /gens/new.json
  def new
    @gen = Gen.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gen }
    end
  end

  # GET /gens/1/edit
  def edit
    @gen = Gen.find(params[:id])
  end

  # POST /gens
  # POST /gens.json
  def create
    @gen = Gen.new(params[:gen])

    respond_to do |format|
      if @gen.save
        format.html { redirect_to @gen, notice: 'Gen was successfully created.' }
        format.json { render json: @gen, status: :created, location: @gen }
      else
        format.html { render action: "new" }
        format.json { render json: @gen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gens/1
  # PUT /gens/1.json
  def update
    @gen = Gen.find(params[:id])

    respond_to do |format|
      if @gen.update_attributes(params[:gen])
        format.html { redirect_to @gen, notice: 'Gen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gens/1
  # DELETE /gens/1.json
  def destroy
    @gen = Gen.find(params[:id])
    @gen.destroy

    respond_to do |format|
      format.html { redirect_to gens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/quartiers_controller.rb
class QuartiersController < ApplicationController
  # GET /quartiers
  # GET /quartiers.json
  def index
    @quartiers = Quartier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quartiers }
    end
  end

  # GET /quartiers/1
  # GET /quartiers/1.json
  def show
    @quartier = Quartier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quartier }
    end
  end

  # GET /quartiers/new
  # GET /quartiers/new.json
  def new
    @quartier = Quartier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quartier }
    end
  end

  # GET /quartiers/1/edit
  def edit
    @quartier = Quartier.find(params[:id])
  end

  # POST /quartiers
  # POST /quartiers.json
  def create
    @quartier = Quartier.new(params[:quartier])

    respond_to do |format|
      if @quartier.save
        format.html { redirect_to @quartier, notice: 'Quartier was successfully created.' }
        format.json { render json: @quartier, status: :created, location: @quartier }
      else
        format.html { render action: "new" }
        format.json { render json: @quartier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quartiers/1
  # PUT /quartiers/1.json
  def update
    @quartier = Quartier.find(params[:id])

    respond_to do |format|
      if @quartier.update_attributes(params[:quartier])
        format.html { redirect_to @quartier, notice: 'Quartier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quartier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quartiers/1
  # DELETE /quartiers/1.json
  def destroy
    @quartier = Quartier.find(params[:id])
    @quartier.destroy

    respond_to do |format|
      format.html { redirect_to quartiers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/villes_controller.rb
class VillesController < ApplicationController
  # GET /villes
  # GET /villes.json
  def index
    @villes = Ville.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @villes }
    end
  end

  # GET /villes/1
  # GET /villes/1.json
  def show
    @ville = Ville.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ville }
    end
  end

  # GET /villes/new
  # GET /villes/new.json
  def new
    @ville = Ville.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ville }
    end
  end

  # GET /villes/1/edit
  def edit
    @ville = Ville.find(params[:id])
  end

  # POST /villes
  # POST /villes.json
  def create
    @ville = Ville.new(params[:ville])

    respond_to do |format|
      if @ville.save
        format.html { redirect_to @ville, notice: 'Ville was successfully created.' }
        format.json { render json: @ville, status: :created, location: @ville }
      else
        format.html { render action: "new" }
        format.json { render json: @ville.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /villes/1
  # PUT /villes/1.json
  def update
    @ville = Ville.find(params[:id])

    respond_to do |format|
      if @ville.update_attributes(params[:ville])
        format.html { redirect_to @ville, notice: 'Ville was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ville.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villes/1
  # DELETE /villes/1.json
  def destroy
    @ville = Ville.find(params[:id])
    @ville.destroy

    respond_to do |format|
      format.html { redirect_to villes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gens_helper.rb
module GensHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/quartiers_helper.rb
module QuartiersHelper
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/views/gens/_form.html.erb
<%= form_for(@gen) do |f| %>
  <% if @gen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gen.errors.count, "error") %> prohibited this gen from being saved:</h2>

      <ul>
      <% @gen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prenom %><br />
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :pseudo %><br />
    <%= f.text_field :pseudo %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gens/edit.html.erb
<h1>Editing gen</h1>

<%= render 'form' %>

<%= link_to 'Show', @gen %> |
<%= link_to 'Back', gens_path %>

app/views/gens/index.html.erb
<h1>Listing gens</h1>

<table>
  <tr>
    <th>Prenom</th>
    <th>Nom</th>
    <th>Pseudo</th>
    <th>Password</th>
    <th>Avatar</th>
    <th>Email</th>
    <th>Dob</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gens.each do |gen| %>
  <tr>
    <td><%= gen.prenom %></td>
    <td><%= gen.nom %></td>
    <td><%= gen.pseudo %></td>
    <td><%= gen.password %></td>
    <td><%= gen.avatar %></td>
    <td><%= gen.email %></td>
    <td><%= gen.dob %></td>
    <td><%= link_to 'Show', gen %></td>
    <td><%= link_to 'Edit', edit_gen_path(gen) %></td>
    <td><%= link_to 'Destroy', gen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gen', new_gen_path %>

app/views/gens/new.html.erb
<h1>New gen</h1>

<%= render 'form' %>

<%= link_to 'Back', gens_path %>

app/views/gens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prenom:</b>
  <%= @gen.prenom %>
</p>

<p>
  <b>Nom:</b>
  <%= @gen.nom %>
</p>

<p>
  <b>Pseudo:</b>
  <%= @gen.pseudo %>
</p>

<p>
  <b>Password:</b>
  <%= @gen.password %>
</p>

<p>
  <b>Avatar:</b>
  <%= @gen.avatar %>
</p>

<p>
  <b>Email:</b>
  <%= @gen.email %>
</p>

<p>
  <b>Dob:</b>
  <%= @gen.dob %>
</p>


<%= link_to 'Edit', edit_gen_path(@gen) %> |
<%= link_to 'Back', gens_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>



<%= link_to "news", news_index_path %>
<%= link_to "gens", gens_path %>
<%= link_to "quartiers", quartiers_path %>
<%= link_to "villes", villes_path %>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squonk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br />
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :texte %><br />
    <%= f.text_area :texte %>
  </div>
  <div class="field">
    <%= f.label :resource %><br />
    <%= f.text_field :resource %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <tr>
    <th>Titre</th>
    <th>Texte</th>
    <th>Resource</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.titre %></td>
    <td><%= news.texte %></td>
    <td><%= news.resource %></td>
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titre:</b>
  <%= @news.titre %>
</p>

<p>
  <b>Texte:</b>
  <%= @news.texte %>
</p>

<p>
  <b>Resource:</b>
  <%= @news.resource %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/quartiers/_form.html.erb
<%= form_for(@quartier) do |f| %>
  <% if @quartier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quartier.errors.count, "error") %> prohibited this quartier from being saved:</h2>

      <ul>
      <% @quartier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :coordonnees %><br />
    <%= f.text_field :coordonnees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quartiers/edit.html.erb
<h1>Editing quartier</h1>

<%= render 'form' %>

<%= link_to 'Show', @quartier %> |
<%= link_to 'Back', quartiers_path %>

app/views/quartiers/index.html.erb
<h1>Listing quartiers</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Coordonnees</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quartiers.each do |quartier| %>
  <tr>
    <td><%= quartier.nom %></td>
    <td><%= quartier.coordonnees %></td>
    <td><%= link_to 'Show', quartier %></td>
    <td><%= link_to 'Edit', edit_quartier_path(quartier) %></td>
    <td><%= link_to 'Destroy', quartier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quartier', new_quartier_path %>

app/views/quartiers/new.html.erb
<h1>New quartier</h1>

<%= render 'form' %>

<%= link_to 'Back', quartiers_path %>

app/views/quartiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @quartier.nom %>
</p>

<p>
  <b>Coordonnees:</b>
  <%= @quartier.coordonnees %>
</p>


<%= link_to 'Edit', edit_quartier_path(@quartier) %> |
<%= link_to 'Back', quartiers_path %>

app/views/villes/_form.html.erb
<%= form_for(@ville) do |f| %>
  <% if @ville.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ville.errors.count, "error") %> prohibited this ville from being saved:</h2>

      <ul>
      <% @ville.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :coordonnees %><br />
    <%= f.text_field :coordonnees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/villes/edit.html.erb
<h1>Editing ville</h1>

<%= render 'form' %>

<%= link_to 'Show', @ville %> |
<%= link_to 'Back', villes_path %>

app/views/villes/index.html.erb
<h1>Listing villes</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Coordonnees</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @villes.each do |ville| %>
  <tr>
    <td><%= ville.nom %></td>
    <td><%= ville.coordonnees %></td>
    <td><%= link_to 'Show', ville %></td>
    <td><%= link_to 'Edit', edit_ville_path(ville) %></td>
    <td><%= link_to 'Destroy', ville, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ville', new_ville_path %>

app/views/villes/new.html.erb
<h1>New ville</h1>

<%= render 'form' %>

<%= link_to 'Back', villes_path %>

app/views/villes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @ville.nom %>
</p>

<p>
  <b>Coordonnees:</b>
  <%= @ville.coordonnees %>
</p>


<%= link_to 'Edit', edit_ville_path(@ville) %> |
<%= link_to 'Back', villes_path %>